### ISSUE TITLE
Johns Hopkins stopped reporting Recovered numbers

### ISSUE THREAD

**Issue by daniel-karl** [daniel-karl/covid19-map#34]
Oh no! What are we gonna do? @baentsch

**Comment by daniel-karl** [comment]
I suggest we add a combo box where users can select a data source

Option 1) Johns Hopkins until March 23 (with recovered)
Option 2)_ Johns Hopkins from March 24 (without recovered)

**Comment by daniel-karl** [comment]
Johns Hopkins is now only reporting Confirmed and Deaths:
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

I suggest we infer Recovered by saying "whoever did not die within the last X weeks counts as recovered/not infectious"
and we can set X to 2 or 4 by default, but allow the users to modify - i think this is much better than counting recovered cases in newspapers anyways - that's intractible

**Comment by daniel-karl** [comment]
Also found this: 
https://github.com/ulklc/covid19-timeseries

**Comment by daniel-karl** [comment]
fixed with custom model to assess recovered cases

**Comment by baentsch** [comment]
As per Slack discussion, we *very likely* have to revisit this based on clinical studies... Here's the [CDC](https://www.cdc.gov/coronavirus/2019-ncov/hcp/clinical-guidance-management-patients.html) with lots of caveats and probabilities -- a more simple (implementable) one is [this](https://www.businessinsider.com/coronavirus-covid19-day-by-day-symptoms-patients-2020-2?r=US&IR=T) speaking for 17 days (from hospital admission to recovery) -- assuming hospital admission is the moment of first be(com)ing a confirmed case... Also [this](https://www.iflscience.com/health-and-medicine/a-daybyday-breakdown-of-coronavirus-symptoms-shows-how-the-disease-covid19-goes-from-bad-to-worse/) talks about 2.5 weeks from hospital admission to release.

**Comment by baentsch** [comment]
After viewing your model in action around days 12-18 based on the above, it's clearly too optimistic. This of course may have to do with the fact that test results come back only some time after hospitalisation -- and *that* can be country-dependent.

A more important thought is this: I was unable to get v1 and v2 figures to match across the globe: When I found a setting where v1 & v2 roughly coincided for Italy (11 days), it's clearly wrong for China or even Switzerland -- then it dawned on me that one cannot do such simple 'looking-back-the-past-few-days' extrapolation because countries are in different stages of the pandemic (accordingly, China with this logic will have hardly any active cases any more with a setting of 11 days - as they're "ahead" of Italy, and UK many more -- as they're trailing Italy). So, I'm afraid we'd need to "baseline" things as to where each country stands relative to the outbreak (e.g., the day 100 cases have been crossed --or maybe 30 for small countries): Same thought as before for the "prediction view".

....

Some more thoughts later: I'm clearly no epidemiologist and wouldn't want to propose something so shy of knowledge... Might it be a better idea to try to touch base with true experts (maybe starting with JH? They may (also) like the idea of recovery projections to improve the spirit of people....)

**Comment by daniel-karl** [comment]
dropped recovery model for now
